In [1]:
import numpy as np
import tensorflow as tf

### playing around

In [2]:
2+3

5

In [134]:
bandits = [0.2,0,-0.2,-5]
num_bandits = len(bandits)


def pullBandit(bandit_index):
    if bandit_index >= num_bandits:
        return -10.0
    result = np.random.randn(1)
    if result > bandits[bandit_index]:
        return 1.0
    else:
        return -1.0

In [128]:
tf.reset_default_graph()
W = tf.Variable(np.ones([num_bandits]), dtype=tf.float32, name='W')
a = tf.argmax(W,0)

In [129]:
reward_holder = tf.placeholder(shape=[1], dtype=tf.float32, name='reward_holder')
action_holder = tf.placeholder(shape=[1], dtype=tf.int32, name='action_holder')

w = tf.slice(W, action_holder, [1])

loss = -1.0 * tf.log(w)*reward_holder

optimizer = tf.train.GradientDescentOptimizer(learning_rate=.01)
update = optimizer.minimize(loss)

In [139]:
num_episodes = 20
e = 0.01
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for i in range(num_episodes):
        j = 0
        rAll = 0
        s = 0
        total_reward = np.zeros(num_bandits)
        while j <= 99:
            j += 1
            if np.random.rand() < e:
                s = np.random.randint(num_bandits)
            r = pullBandit(s)
            total_reward[s] += r

            rAll += r
            _, res, WW, action  = sess.run([update, w, W, a], {reward_holder:[rAll], action_holder:[action]})

            s = action


        print total_reward     

[ 100.    0.    0.    0.]
[ 99.   0.   0.   1.]
[ 99.   0.  -1.   0.]
[ 98.   0.   0.   0.]
[ 100.    0.    0.    0.]
[ 98.  -1.   0.   1.]
[ 99.  -1.   0.   0.]
[ 97.   0.   0.   1.]
[ 99.  -1.   0.   0.]
[ 99.  -1.   0.   0.]
[ 99.   0.   0.   1.]
[ 100.    0.    0.    0.]
[ 100.    0.    0.    0.]
[ 99.   0.   1.   0.]
[ 99.   0.   0.   1.]
[ 100.    0.    0.    0.]
[ 99.   0.   0.   1.]
[ 100.    0.    0.    0.]
[ 99.   0.   1.   0.]
[ 100.    0.    0.    0.]
